services:
  - type: web
    name: skyradar
    runtime: node
    plan: free
    branch: master
    buildCommand: npm install --include=dev && npm --prefix server install --include=dev && npm --prefix client install --include=dev && npm run build
    startCommand: npm run start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: POLL_INTERVAL_MS
        value: 15000
